// Productos importados de UMM (umma.io)
// Generado automáticamente por scripts/setup-umma-products.py
// 
// PRÓXIMOS PASOS:
// 1. Revisar y completar cada producto (ingredientes, cómo usar, etc.)
// 2. Reemplazar placeholders con fotos reales
// 3. Importar en products.ts o usar directamente en la app

import type { Product } from './products'

const img = (slug: string) => `/images/products/${slug}/main.webp`

export const ummaProducts: Product[] = [
  {
    id: 'anua-pdrn-cleansing-foam',
    slug: 'anua-pdrn-cleansing-foam',
    name: 'Anua PDRN Cleansing Foam',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 32.3,
    color: '#1a4a4a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('anua-pdrn-cleansing-foam')]
  },

  {
    id: 'manyo-pure-cleansing-oil',
    slug: 'manyo-pure-cleansing-oil',
    name: 'Manyo Pure Cleansing Oil',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 48.3,
    color: '#1a1a1a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('manyo-pure-cleansing-oil')]
  },

  {
    id: 'vt-pdrn-cleanser',
    slug: 'vt-pdrn-cleanser',
    name: 'VT PDRN Cleanser',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 38.3,
    color: '#2a4a3a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('vt-pdrn-cleanser')]
  },

  {
    id: 'anua-niacinamide-txa-toner',
    slug: 'anua-niacinamide-txa-toner',
    name: 'Anua Niacinamide TXA Toner',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 48.4,
    color: '#3a2a4a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('anua-niacinamide-txa-toner')]
  },

  {
    id: 'anua-peach-77-toner',
    slug: 'anua-peach-77-toner',
    name: 'Anua Peach 77 Toner',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 29.95,
    color: '#4a2a3a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('anua-peach-77-toner')]
  },

  {
    id: 'im-from-rice-toner',
    slug: 'im-from-rice-toner',
    name: 'I'M FROM Rice Toner',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 40.45,
    color: '#f5f5dc',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('im-from-rice-toner')]
  },

  {
    id: 'goodal-vitamin-c-serum',
    slug: 'goodal-vitamin-c-serum',
    name: 'Goodal Vitamin C Serum',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 53.85,
    color: '#2a5a3a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('goodal-vitamin-c-serum')]
  },

  {
    id: 'jumiso-niacinamide-serum',
    slug: 'jumiso-niacinamide-serum',
    name: 'Jumiso Niacinamide Serum',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 179.0,
    color: '#4a3a5a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('jumiso-niacinamide-serum')]
  },

  {
    id: 'beauty-of-joseon-eye-serum',
    slug: 'beauty-of-joseon-eye-serum',
    name: 'Beauty of Joseon Eye Serum',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 33.0,
    color: '#2a1a1a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('beauty-of-joseon-eye-serum')]
  },

  {
    id: 'vt-cica-collagen-eye-cream',
    slug: 'vt-cica-collagen-eye-cream',
    name: 'VT Cica Collagen Eye Cream',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 40.25,
    color: '#1a3a2a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('vt-cica-collagen-eye-cream')]
  },

  {
    id: 'tocobo-bio-watery-sun',
    slug: 'tocobo-bio-watery-sun',
    name: 'Tocobo Bio Watery Sun',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 33.65,
    color: '#4a6a8a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('tocobo-bio-watery-sun')]
  },

  {
    id: 'round-lab-birch-juice-sunscreen',
    slug: 'round-lab-birch-juice-sunscreen',
    name: 'Round Lab Birch Juice Sunscreen',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 135.2,
    color: '#3a5a4a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('round-lab-birch-juice-sunscreen')]
  },

  {
    id: 'some-by-mi-real-cica-mask',
    slug: 'some-by-mi-real-cica-mask',
    name: 'Some By Mi Cica Mask',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 3.1,
    color: '#2a6a4a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('some-by-mi-real-cica-mask')]
  },

  {
    id: 'dr-jart-ceramidin-mask',
    slug: 'dr-jart-ceramidin-mask',
    name: 'Dr. Jart+ Ceramidin Mask',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 48.55,
    color: '#1a2a3a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('dr-jart-ceramidin-mask')]
  },

  {
    id: 'dr-althea-345-relief-cream',
    slug: 'dr-althea-345-relief-cream',
    name: 'Dr. Althea 345 Relief Cream',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 50.4,
    color: '#3a3a4a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('dr-althea-345-relief-cream')]
  },

  {
    id: 'vt-pdrn-capsule-cream',
    slug: 'vt-pdrn-capsule-cream',
    name: 'VT PDRN Capsule Cream',
    category: 'K-Beauty',
    benefit: 'Producto K-Beauty seleccionado por ONNI',
    micro: 'Disponible en umma.io',
    price: 43.65,
    color: '#2a3a5a',
    skinType: 'all' as const,
    climateTags: ['tropical', 'humid'],
    bestSeller: false,
    vegan: false,
    crueltyFree: true,
    popularity: 0,
    stock: 100,
    volume: 'TBD',
    description: 'Producto importado desde Corea a través de UMM.',
    keyIngredients: [],
    howToUse: [],
    fullIngredients: 'TBD',
    images: [img('vt-pdrn-capsule-cream')]
  },

]
